version: '3.1'

services:
  db:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stickery
    ports:
      -  "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
